{% set name = "astropy-iers-data" %}
{% set version = "0.2023.6.26.17.14.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astropy-iers-data-{{ version }}.tar.gz
  sha256: 312193a80e73035caaf0d2ea569e84ef7ab2d666c6d27d3d2880578766c11ba5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - astropy_iers_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropy/astropy-iers-data/
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
