{% set name = "astropy-iers-data" %}
{% set version = "0.2025.11.10.0.38.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 487dc974b9a5114ac75ff4fd96244e8fa7d07e1504092f7c2b8138c2b9c842e9

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python

test:
  imports:
    - astropy_iers_data
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/astropy/astropy-iers-data
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  description: |
    The iers package provides access to the tables provided by the International Earth Rotation
    and Reference Systems (IERS) service, in particular the Earth Orientation data allowing
    interpolation of published UT1-UTC and polar motion values for given times.
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  doc_url: https://docs.astropy.org/en/latest/utils/iers.html
  dev_url: https://github.com/astropy/astropy-iers-data

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
