{% set name = "astropy-iers-data" %}
{% set version = "0.2023.10.4.22.8.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astropy-iers-data-{{ version }}.tar.gz
  sha256: 9459ee2393e007e30f7dcca280f831f19ba641c66d4fba7ae538c167f7129faa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - astropy_iers_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropy/astropy-iers-data/
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
