{% set name = "astropy-iers-data" %}
{% set version = "0.2025.6.23.0.39.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3dd7cbf82408837ad21fb15db0c35d0bff19b1552f6b13de48542a246215a754

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python

test:
  imports:
    - astropy_iers_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropy/astropy-iers-data/
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  description: |
    The iers package provides access to the tables provided by the International Earth Rotation
    and Reference Systems (IERS) service, in particular the Earth Orientation data allowing
    interpolation of published UT1-UTC and polar motion values for given times.
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  doc_url: https://docs.astropy.org/en/latest/utils/iers.html
  dev_url: https://github.com/astropy/astropy-iers-data/

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
